const adherentbutton = document.getElementById("adherent");
const adherentdiv = document.getElementById("adherentcontent");
const famillebutton = document.getElementById("famille");
const famillediv = document.getElementById("famillecontent");
const handicapbutton = document.getElementById("handicap");
const handicapdiv = document.getElementById("handicapcontent");
const proassobutton = document.getElementById("proasso");
const proassodiv = document.getElementById("profcontent");
const enseignantsbutton = document.getElementById("enseignants");
const enseignantsdiv = document.getElementById("enseignantcontent");
const cherchetubutton = document.getElementById("cherchetu");
const cherchetudiv = document.getElementById("chercheurscontent");

adherentbutton.addEventListener("click", function () {
  adherentbutton.classList.add("active");
  famillebutton.classList.remove("active");
  handicapbutton.classList.remove("active");
  proassobutton.classList.remove("active");
  enseignantsbutton.classList.remove("active");
  cherchetubutton.classList.remove("active");
  adherentdiv.classList.add("visible");
  adherentdiv.classList.remove("hidden");
  famillediv.classList.add("hidden");
  handicapdiv.classList.add("hidden");
  proassodiv.classList.add("hidden");
  enseignantsdiv.classList.add("hidden");
  cherchetudiv.classList.add("hidden");
});
famillebutton.addEventListener("click", function () {
  adherentbutton.classList.remove("active");
  famillebutton.classList.add("active");
  handicapbutton.classList.remove("active");
  proassobutton.classList.remove("active");
  enseignantsbutton.classList.remove("active");
  cherchetubutton.classList.remove("active");
  adherentdiv.classList.add("hidden");
  famillediv.classList.add("visible");
  famillediv.classList.remove("hidden");
  handicapdiv.classList.add("hidden");
  proassodiv.classList.add("hidden");
  enseignantsdiv.classList.add("hidden");
  cherchetudiv.classList.add("hidden");
});
handicapbutton.addEventListener("click", function () {
  adherentbutton.classList.remove("active");
  famillebutton.classList.remove("active");
  handicapbutton.classList.add("active");
  proassobutton.classList.remove("active");
  enseignantsbutton.classList.remove("active");
  cherchetubutton.classList.remove("active");
  adherentdiv.classList.add("hidden");
  famillediv.classList.add("hidden");
  handicapdiv.classList.add("visible");
  handicapdiv.classList.remove("hidden");
  proassodiv.classList.add("hidden");
  enseignantsdiv.classList.add("hidden");
  cherchetudiv.classList.add("hidden");
});
proassobutton.addEventListener("click", function () {
  adherentbutton.classList.remove("active");
  famillebutton.classList.remove("active");
  handicapbutton.classList.remove("active");
  proassobutton.classList.add("active");
  enseignantsbutton.classList.remove("active");
  cherchetubutton.classList.remove("active");
  adherentdiv.classList.add("hidden");
  famillediv.classList.add("hidden");
  handicapdiv.classList.add("hidden");
  proassodiv.classList.add("visible");
  proassodiv.classList.remove("hidden");
  enseignantsdiv.classList.add("hidden");
  cherchetudiv.classList.add("hidden");
});
enseignantsbutton.addEventListener("click", function () {
  adherentbutton.classList.remove("active");
  famillebutton.classList.remove("active");
  handicapbutton.classList.remove("active");
  proassobutton.classList.remove("active");
  enseignantsbutton.classList.add("active");
  cherchetubutton.classList.remove("active");
  adherentdiv.classList.add("hidden");
  famillediv.classList.add("hidden");
  handicapdiv.classList.add("hidden");
  proassodiv.classList.add("hidden");
  enseignantsdiv.classList.add("visible");
  enseignantsdiv.classList.remove("hidden");
  cherchetudiv.classList.add("hidden");
});
cherchetubutton.addEventListener("click", function () {
  adherentbutton.classList.remove("active");
  famillebutton.classList.remove("active");
  handicapbutton.classList.remove("active");
  proassobutton.classList.remove("active");
  enseignantsbutton.classList.remove("active");
  cherchetubutton.classList.add("active");
  adherentdiv.classList.add("hidden");
  famillediv.classList.add("hidden");
  handicapdiv.classList.add("hidden");
  proassodiv.classList.add("hidden");
  enseignantsdiv.classList.add("hidden");
  cherchetudiv.classList.add("visible");
  cherchetudiv.classList.remove("hidden");
});
